<a href="https://colab.research.google.com/github/EshraqAllawama/MyDataScienceJourney/blob/main/Data_Analysis/numpy/First_lecture_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy based on Lanier algebra (Matrix)
# you need this library and another library's based on it as pandas
# Numpy is also incredibly fast, as it has bindings to C libraries.

In [ ]:
# vector -> 1 dim
# matrix -> 2 dim or 1

In [ ]:
import numpy as np

In [ ]:
# array is class
my_list_1 = [1, 2, 3, 5]
np.array(my_list_1)

array([1, 2, 3, 5])

In [ ]:
my_list_2 = [[1, 3, 4], [5, 6, 7]]
np.array(my_list_2)

array([[1, 3, 4],
       [5, 6, 7]])

#create the array using numpy

In [ ]:
# Return evenly spaced numbers over a specified interval.
# not randomly , البعد بينهم متساوي , equals gap
np.arange(0, 13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(0, 13, 2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [ ]:
# np.zeros(shape)
np.zeros(3) # as Victor

array([0., 0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
       # dim1, dim2
np.zeros((3,4)) # as matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
      # dim1, dim2, dim3    3 dimensional using for picture coloring
np.zeros((3,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Return evenly spaced numbers over a specified interval.
# not randomly , البعد بينهم متساوي , equals gap
          #start,last,# of number
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.linspace(0, 5, 2)

array([0., 5.])

In [ ]:
np.linspace(0, 5, 3)

#Identity matrix

In [ ]:
      # shape
np.eye(3) # is square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Random is sub module

In [ ]:
# These numbers are called "pseudo-random"


In [ ]:
# uniform distribution over [0, 1) -> Continuous(float mostly) Uniform Distribution
# كل القيم الها نفس احتمالية الظهور, مثلا زي حجر النرد
np.random.rand(4)

array([0.40137486, 0.69955041, 0.02680229, 0.41732899])

In [ ]:
# random.rand(d0, d1, ..., dn)
np.random.rand(3,3)

array([[0.76969591, 0.19078357, 0.3156791 ],
       [0.41613771, 0.44433192, 0.35183025],
       [0.39926887, 0.97141282, 0.63570639]])

In [ ]:
import numpy as np


In [ ]:
# standard normal distribution.
# كل القيم  ما الها نفس احتمالية الظهور
np.random.randn(4)


array([ 0.68350149, -1.09637341,  0.90997447, -0.13072766])

In [ ]:
# Return random integers from low (inclusive) to high (exclusive).

In [ ]:
# discrete(int mostly) uniform distribution
                        # shape
np.random.randint(0, 101, 33)

array([ 4, 81, 61, 17, 32, 29, 99, 14,  1, 29, 75, 84, 40, 35, 44, 16, 70,
       18, 82,  1, 57, 81, 97, 34, 38, 48, 97, 61, 24, 40,  4,  2, 38])

In [ ]:
# new shape should be compatible with the original shape
# Returns an array containing the same data with a new shape.

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
# Returns an array containing the same data with a new shape.
np.reshape(arr, (5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.reshape(5,2)

array([[39, 49],
       [37, 41],
       [31, 34],
       [26, 33],
       [43,  1]])

In [ ]:
ranarr

array([39, 49, 37, 41, 31, 34, 26, 33, 43,  1])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmax() # the location/index of max value
     # using in classification modules (التصنيف)
     # بتعطي الاندكس لاعلى كلاس او صنف احتمالية

1

In [ ]:
ranarr.argmin() # the location/index of min value

9

#Shape

In [ ]:
ranarr

array([39, 49, 37, 41, 31, 34, 26, 33, 43,  1])

In [ ]:
# as attributes
ranarr.shape # as tuple

(10,)

In [ ]:
ranarr.reshape(1, 10) # for somthing in nural networks


array([[39, 49, 37, 41, 31, 34, 26, 33, 43,  1]])

In [ ]:
ranarr.shape

(10,)

In [ ]:
ranarr.reshape(1, 10).shape# the calculate shape direct in using reshape

(1, 10)

In [ ]:
ranarr.reshape(10, 1).shape

(10, 1)

In [ ]:
# the vaule in array the same type, invert list
ranarr.dtype

dtype('int64')