<a href="https://colab.research.google.com/github/EshraqAllawama/MyDataScienceJourney/blob/main/Data_Analysis/numpy/Third_lecture_Numpy_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arithmetic operations
elemant wise, eash value with eash value,
corresponding to him, must the same shape


In [ ]:
import numpy as np

arr = np.arange(0,10)
# arr_2 = np.zeros(11) not the same shape
arr_2 = np.zeros(10)
arr_3 = np.ones(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr_2 + arr_3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr_2 - arr_3

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [ ]:
arr_2 * arr_3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_2 / arr_3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Warning on zero division by zero, but not an error!
# Just replaced with nan
arr_2 / arr_2

<ipython-input-24-e7d1fa6f147e>:3: RuntimeWarning: invalid value encountered in divide
  arr_2 / arr_2


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [ ]:
# Also warning, but not an error instead infinity
arr_3 / arr_2

<ipython-input-25-9d5667ac7107>:1: RuntimeWarning: divide by zero encountered in divide
  arr_3 / arr_2


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
# Broadcasting : operation apply on full array
1 / arr

<ipython-input-26-8e9ff3643be7>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # Broadcasting


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
# Broadcasting
arr ** 3

Universal Array Functions

In [ ]:
# element wise of apply on all array  and Broadcasting
# agreeget Methods

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr) # e^arr -> e = 2.71828183e
# e^0 = 1
# log_e 1 = 0

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.log(arr)

<ipython-input-45-0a7f062109fe>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.max(arr)

9

In [ ]:
arr.max()

9

In [ ]:
np.min(arr)

0

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [ ]:
test = np.array([0, np.pi/6, np.pi])

In [ ]:
#  الراديان وليس الدرجات
test_1 = np.cos(test)

In [ ]:
test_1

array([ 1.       ,  0.8660254, -1.       ])

In [ ]:
tt

array([ 57.29577951,  49.61960059, -57.29577951])

In [ ]:
np.radians(test_1)

array([ 0.01745329,  0.00872665, -0.01745329])

In [ ]:
np.cos(test_1 * (np.radians(np.pi)/180))

array([0.99999995, 0.99999999, 0.99999995])

In [ ]:
import math as m
m.sin(180)

-0.8011526357338304